version: '3'
services:
  peer1:
    container_name: peer1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - TRACKER_IP=172.20.0.6:5000
    networks:
      mynet:
        ipv4_address: 172.20.0.2
  peer2:
    container_name: peer2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - TRACKER_IP=172.20.0.6:5000
    networks:
      mynet:
        ipv4_address: 172.20.0.3
  peer3:
    container_name: peer3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - TRACKER_IP=172.20.0.6:5000
    networks:
      mynet:
        ipv4_address: 172.20.0.4
  peer4:
    container_name: peer4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - TRACKER_IP=172.20.0.6:5000
    networks:
      mynet:
        ipv4_address: 172.20.0.5
networks:
  mynet:
    external:
      name: mynet